package com.github.houbb.data.factory.core.exception;

import org.junit.jupiter.api.Test;

/**
* <p> DataFactoryRuntimeException Tester. </p>
* <p> 2019-02-26 16:20:40.542 </p>
*
* @author binbin.hou
* @version 0.0.1-SNAPSHOT
*/
public class DataFactoryRuntimeExceptionTest {

    /**
    *
    * Method: DataFactoryRuntimeException()
    */
    @Test
    public void DataFactoryRuntionExceptionTest() throws Exception {
    }

    /**
    *
    * Method: DataFactoryRuntimeException(message)
    */
    @Test
    public void DataFactoryRuntionExceptionMessageTest() throws Exception {
    }

    /**
    *
    * Method: DataFactoryRuntimeException(message, cause)
    */
    @Test
    public void DataFactoryRuntionExceptionMessageCauseTest() throws Exception {
    }

    /**
    *
    * Method: DataFactoryRuntimeException(cause)
    */
    @Test
    public void DataFactoryRuntionExceptionCauseTest() throws Exception {
    }

    /**
    *
    * Method: DataFactoryRuntimeException(message, cause, enableSuppression, writableStackTrace)
    */
    @Test
    public void DataFactoryRuntionExceptionMessageCauseEnableSuppressionWritableStackTraceTest() throws Exception {
    }


}
